/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_LibWrapper */

#ifndef _Included_com_example_jni_LibWrapper
#define _Included_com_example_jni_LibWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_LibWrapper
 * Method:    SendBuffer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jni_LibWrapper_SendBuffer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_jni_LibWrapper
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jni_LibWrapper_Init
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
